### PR TITLE
add more text

### LINKED ISSUE #2: Make icons and images responsive

### PR DESCRIPTION
**Pull request by dingaaling**
- add Mission/Contact Text
- add bulleted list for features next to carousel
- some text styling changes

now fixes #2 and #3

### CODE REVIEW

**Comment by dingaaling** [comment]
Note: the bulleted list is current not responsive and will be hidden by the carousel on mobile atm

To Do: make icons and bulleted list responsive

**Comment by dabreegster** [comment]
It's looking awesome! Let me know when you need real pictures and bullet text for the carousel. And if we want to try animations there (I really think it'd be helpful to create that sense of "aliveness" for the traffic simulation, at least), is GIF or MP4 or something else preferred?

**Comment by dingaaling** [comment]
Yes please do go ahead and share content! Pictures or short gifs and text

**Comment by dabreegster** [comment]
Carousel content below!

# A/B Street - traffic simulator

link to https://a-b-street.github.io/docs/software/abstreet.html for more details

- edit roads and intersections
- visualize drivers, buses, pedestrians, and cyclists moving around
- see how changes affect people's travel time and safety

Screenshot below. It's a bit hard to choose just one; the full page kind of splits out exploring the map, watching movement, editing stuff, and measuring changes.
Screenshot from 2022-05-16 12-43-24


# Ungap the Map

https://a-b-street.github.io/docs/software/ungap_the_map/index.html

- see existing cycling infrastructure
- explore routing tradeoffs between speed, safety, and avoiding hills
- fill in missing links in the cycle network
- predict how many people will decide to cycle

Screenshot from 2022-05-16 12-46-13


# 15-minute neighbourhoods

https://a-b-street.github.io/docs/software/fifteen_min.html

- see what shops, libraries, health facilities, etc are reachable within a 15-minute walk or cycle ride
- find houses meeting your own definition of walkability

Screenshot from 2022-05-16 12-46-56

# 15-minute Santa

https://a-b-street.github.io/docs/software/santa.html

- a game teaching the importance of letting people live close to where they work and shop
- deliver presents around Seattle as efficiently as possible
- create new shops near residential areas to improve your score

Screenshot from 2022-05-16 12-50-07


# Low-traffic neighbourhoods

https://a-b-street.github.io/docs/software/ltn/index.html

- understand how drivers may find shortcuts through neighbourhoods
- experiment with modal filter placement to create more liveable residential streets

ltn

**Comment by dingaaling** [comment]
@dabreegster carousel paired text is now responsive. thanks for the help @MarcoBerlot!

https://user-images.githubusercontent.com/5104098/169716486-ab55e6f6-733b-4f6c-ac58-6227ecffaba5.mov

**Pull request merged**
